CREATE DATABASE sql_database;
SHOW DATABASES;
DROP DATABASE TEST;
DROP DATABASE testdatabase;
CREATE TABLE employee
(id INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(20) NOT NULL,
surname VARCHAR(20) NOT NULL,
team VARCHAR(20) NOT NULL);
CREATE TABLE employer
(id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(20) NOT NULL,
surname VARCHAR(20) NOT NULL,
team VARCHAR(20) NOT NULL,
FOREIGN KEY (id) references employee(id));